classDiagram
	class User_Model {
		Int id
		String name
		Status status
		Role roles
		TABLE_MAPPER "users"
	}
	class Role_Model {
		Int id
		String name
		String? description
		Int user_id
		User user
		TABLE_MAPPER "roles"
	}
	class Status_Enum {
		ACTIVE
		INACTIVE
	}

